services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab
    # hostname: foxinstudio.fr
    shm_size: 256m
    ports:
      - 443:443
      - 80:80
      - 22:22
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
volumes:
  gitlab-data:
  gitlab-config:
  gitlab-logs: